### ISSUE TITLE
"Notice: Undefined index: connection_settings" using Symfony4

### ISSUE THREAD

**Issue by jvbussel** [sgomez/adldap2-bundle#2]
Is this bundle suitable for Symfony 4?

In services.yaml I do have:

parameters:
    locale: 'en'
    adldap2:
        auto_connect: true
        connection_class: Adldap\Connections\Ldap
        connection_settings:
            domain_controllers: ....
            .

But do get "Notice: Undefined index: connection_settings"

**Comment by sgomez** [comment]
Can you run `composer info` and send me this package and `adldap2/adldap2` installed versions?

Anyway, can you format your configuration with ``` to see it propertly?

Thanks.

**Comment by jvbussel** [comment]
I looked like you update this buble to support Symfony 4.0:

    composer.json : 	Updated to symfony 4

**service.yaml:**

parameters:
....locale: 'en'

....adldap2:
........auto_connect: true
........connection_class: Adldap\Connections\Ldap
........connection_settings:
............domain_controllers:

**composer info:**

adldap2/adldap2                     v7.0.15            A PHP LDAP Package for Active Directory Manipulation.
sgomez/adldap2-bundle               v4.0.0             Symfony Bundle for adldap2 library.

**output of bin/console --verbose:**

In Adldap2Extension.php line 20:
                                                
  [ErrorException]                              
  Notice: Undefined index: connection_settings  
                                                

Exception trace:
 Sgomez\Bundle\Adldap2Bundle\DependencyInjection\Adldap2Extension->load() at /var/www/projects/base/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /var/www/projects/base/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /var/www/projects/base/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/projects/base/vendor/symfony/dependency-injection/ContainerBuilder.php:736
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/projects/base/vendor/symfony/http-kernel/Kernel.php:519
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/projects/base/vendor/symfony/http-kernel/Kernel.php:123
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/projects/base/vendor/symfony/framework-bundle/Console/Application.php:65
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/projects/base/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/projects/base/bin/console:39

**Comment by sgomez** [comment]
AFAIK the configuration should be:

```
parameters:
    locale: 'en'
adldap2:
    auto_connect: true
    connection_class: Adldap\Connections\Ldap
    connection_settings:
        domain_controllers: ....
```


Mine is:

```
adldap2:
    connection_settings:
        domain_controllers: ["%ad_domain_controller%"]
        base_dn: "%ad_base_dn%"
        admin_username: "%ad_admin_username%"
        admin_password: "%ad_admin_password%"
        account_suffix: "%ad_account_suffix%"
        use_ssl: true
```

Check the indentation of your config.
